# Default configuration for scrape-store-agents
# This is the working default config - customize as needed

# Scraper configuration
scraper:
  type: web
  timeout: 30
  max_content_length: 10485760  # 10MB
  extract_links: false
  max_depth: 1
  allowed_domains: []  # Empty means all domains allowed
  blocked_domains: []
  content_selectors:
    - main
    - article
    - .content
    - .post-content
    - .entry-content
  title_selectors:
    - h1
    - title
    - .title
    - .headline

# Vector store configuration
vector_store:
  type: chromadb
  collection_name: documents
  embedding_model: all-MiniLM-L6-v2
  distance_metric: cosine
  persist_directory: ./data/chroma
  # Use ChromaDB container
  host: chromadb
  port: 8000

# API server configuration
api:
  host: 0.0.0.0
  port: 8000
  debug: false
  cors_origins:
    - "*"

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  # file: scrape-store-agents.log

# Scraping sources (add your own!)
sources:
  # Example source - disabled by default
  - name: example-docs
    url: https://docs.python.org/3/tutorial/
    scraper_type: web
    enabled: false
    custom_config:
      max_depth: 2
      content_selectors:
        - .body
        - .section